### ISSUE TITLE
No settings button? cleanup n/a stats

### ISSUE THREAD

**Issue by Megumin230** [Road-block/CharacterStatsPaneImproved#1]
I don't see any setting buttons anywhere or /commands to change anything, I want to use the cleanup n/a stats option to reduce clutter in the character ui.

**Comment by Road-block** [comment]
It should be doing that automatically already.
Note that it only clears stats that actually say `N/A` not zero ones.

**Comment by Megumin230** [comment]
Sorry maybe I got it wrong, Ithought it would only display the stats a class uses, I still see the entire list of all stats
![image](https://github.com/Road-block/CharacterStatsPaneImproved/assets/70694639/5f4fbaeb-b22f-4a82-9cf0-2eb881aa5796)

I thought it would be more direct like retail, where it only displays the stats a class uses
![image](https://github.com/Road-block/CharacterStatsPaneImproved/assets/70694639/59c8dc94-3778-4396-8275-8647583806bf)

Not asking for a different design or anything, just the option to only display certain stats and completely hide others, lmk what you think, and thanks for reading!

**Comment by Road-block** [comment]
I am not looking to recreate the retail stat pane (I'm assuming this is what is shown in the later screenshots) sorry.

I do need to make it show at least the base English terms for the custom stats.

So the addon has no options at the moment. It just does what it does automatically.
In the Classic Client, depending on your class, some few stats instead of being hidden they show as `N/A` (Not-Applicable)

Those are the ones I'm removing only.
If you want a list they are these

- Ranged DPS/Attack Power/Speed/Damage for classes with relic/idol in ranged slot
- Mana Regen/Combat Mana Regen for classes with no Mana

In those cases the Classic client instead of hiding the line it still shows it with a value of `N/A`. Those are the ones my addon removes, not player choices.

**Comment by Road-block** [comment]
Since I have you here.
Any chance you can translate for me 3 terms in your language? 🙏🏻 

1. `Combat Table Coverage` and its abbreviated form `CTC` in English.
2. `Luck`
3. `Gear Checks`

Thank you in advance.
